#PlayerPoints API
#Usa %points% per indicare il numero dei punti di un giocatore
1:
  id: watch
  data: 0
  amount: 1
  name: '&c&lCongegno Inter Servers'
  lore:
  - '&eCliccami per aprire un menu con la lista servers'
  - '&ee scegliere il server in cui giocare'
  command: bs servers
2:
  id: bone
  data: 0
  amount: 1
  name: '&c&lGestore Pet'
  lore:
  - '&eCliccami per aprire il menu per gestire i pet'
  - '&ee gestire i tuoi animaletti domestici'
  command: bs pet
3:
  id: name_tag
  data: 0
  amount: 1
  name: '&bTuoi Gettoni: &a %points% '
  lore:
  - '&eGuarda quanti gettoni hai'
  command: ''